version: "3.8"

services:  
  go-application:
    container_name: go-application
    build: .
    ports: 
      - 8081:8080
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=adminadmin
      - DB_DB=alta_agregasi
      - DB_HOST=godb.cvkjph0grufv.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
    restart: on-failure