version: "3.8"

services:  
  go-application:
    container_name: go-application
    build: .
    ports: 
      - 8081:8080
    environment:
      - DB_USERNAME=rood
      - DB_PASSWORD=
      - DB_DB=alta_agregasi
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
    restart: on-failure